name: Build

on:
  push:
    branches:
    - main
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - uses: actions/checkout@v2

    - run: go mod download

    - run: go test ./...

    - run: go build

  docker:
    name: Docker build and push
    runs-on: ubuntu-latest
    needs: build

    env:
      IMAGE_NAME: grafana-image-to-slack

    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        repository: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tag_with_ref: true
